# Generated by Django 4.2.8 on 2024-02-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('data_arrivo', models.DateField()),
                ('data_partenza', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MembroGruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('data_arrivo', models.DateField()),
                ('data_partenza', models.DateField()),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_gruppi.gruppo')),
            ],
        ),
    ]
