# Generated by Django 4.2.10 on 2024-02-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_gruppi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruppo',
            options={'verbose_name': 'Gruppo', 'verbose_name_plural': 'Gruppi'},
        ),
        migrations.AlterModelOptions(
            name='membrogruppo',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membri'},
        ),
        migrations.AddField(
            model_name='gruppo',
            name='via_soggiorno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membrogruppo',
            name='via_soggiorno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
