# Generated by Django 4.2.10 on 2024-02-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_gruppi', '0002_alter_gruppo_options_alter_membrogruppo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gruppo',
            old_name='via_soggiorno',
            new_name='indirizzo_soggiorno',
        ),
        migrations.RenameField(
            model_name='membrogruppo',
            old_name='via_soggiorno',
            new_name='indirizzo_soggiorno',
        ),
    ]
