# Generated by Django 4.2.10 on 2024-03-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_gruppi', '0004_gruppo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_servizio', models.CharField(max_length=50)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_gruppi.gruppo')),
            ],
        ),
    ]
