# Generated by Django 4.2.10 on 2024-03-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_gruppi', '0005_zoneservizio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoneServizio',
        ),
    ]
