# Generated by Django 4.2.10 on 2024-03-13 07:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_gruppi', '0006_delete_zoneservizio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_servizio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Zona Servizio',
                'verbose_name_plural': 'Zone Servizio',
            },
        ),
        migrations.AddField(
            model_name='gruppo',
            name='zona_servizio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='gestione_gruppi.zoneservizio'),
        ),
    ]
