# Generated by Django 4.2.10 on 2024-03-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_gruppi', '0007_zoneservizio_gruppo_zona_servizio'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrogruppo',
            name='zona_servizio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_gruppi.zoneservizio'),
        ),
    ]
